### ISSUE TITLE
[Feature Request] Tag docker image with version number

### ISSUE THREAD

**Issue by lonix1** [icescrum/iceScrum#42]
The docker image has only one tag: `latest`.

This is not standard practice, because it means you will always pull the latest version. Not a good idea, because you have no control over versioning.

Please consider adding *version tags* (which is how it's done for every open source project).

So for example, the latest version is 7.46 so the image should have tag `7.46`. And so the `latest` tag will point to the `7.46` tag. When image `7.47` is released then the `latest` tag will point to it, etc.

Thanks!

**Comment by noullet** [comment]
Hi @lonix1, no need for this anymore?

**Comment by lonix1** [comment]
@noullet It would be very nice to have docker versioning.

But I don't want you to waste your time if I'm the only one who asked for it - I'm surprised no one else said anything. 🤔 😄

**Comment by lonix1** [comment]
@noullet It would be very nice to have docker versioning.

But I don't want you to waste your time if I'm the only one who asked for it - I'm surprised no one else said anything. 🤔 😄

---
(BTW, the reason I open the issue is, as you know, in many companies the infrastructure is tested, then tested in staging, then deployed to production. So they "pin" the version to be used, because they know "it works". If we use `latest`, then it will pull a new version automatically, and it might break something. Pinning versions allows us to be sure what is deployed is 100% working.)

**Comment by lonix1** [comment]
@noullet On second thought, would you guys be willing to consider this for the next version?

i.e. to tag it as `7.47` (in addition to `latest`).

**Comment by noullet** [comment]
If you make a new install, in most cases it means that you did not have iceScrum already, so fetching the latest image is what you want. If you already have iceScrum installed, then Docker will fetch a new image only if it is instructed to do so, which happens when you actually want to get a newer version and again there are very high chances that you want the latest. These are the reasons why 99% of the times, the `latest` tag is enough for iceScrum.

Nevertheless, we understand that 100% reliability and reproducibility is desirable and should be possible. However, tagged versions does not offer that. Indeed, as a consumer of an image from Docker Hub, you have no guaranty that the version behind a specific tag stays the same. As far as I know, to ensure real reliability and reproducibility, the only way is to maintain your own registry. Actually, if you want real control over what you deploy, the best way consists in maintaining your own Dockerfiles so you are sure of what is actually going on.

To add a bit more context, much like modern browsers, iceScrum is released as frequent minor versons rather than big ones and forward compatibility is ensured without migration procedure. From our experience and user feedback, there is are only downsides of sticking to a specific version of iceScrum.

**Comment by noullet** [comment]
I replied to your comments with old thoughts on the subject but I noticed they do not address what you point out and that they may be obsolete so I preferred deleting my reply! Sorry about that, you can dismiss it if you received it by email.

We have many things currently going on and I am not sure that such change can happen for the next version, however we will consider it in the future.

However, there is a workaround and it is actually the best way to have control over versioning and get reliable deployment: having your own registry.

**Comment by lonix1** [comment]
Okay if it's on your "to do" list that is great. 👍
